### ISSUE TITLE
unrecognized font family ionicons

### ISSUE THREAD

**Issue by RookiePyl** [fangwei716/ThirtyDaysOfReactNative#35]
When i run the .xcodeproj  ,simulator show red warning  `unrecognized font family ionicons` 。

**Comment by pein892** [comment]
You may need run `react-native link`

**Comment by ltt1987** [comment]
I have the same problem, if run `react-native link` command, the build will be failed. Hope you can help. Thanks!

**Comment by fangwei716** [comment]
try react-native link react-native-vector-icons?

**Comment by shangcloud** [comment]
I still have this problem by using all the method above

**Comment by kFoodie** [comment]
me too

**Comment by OceanHorn** [comment]
same problem, not solved.

-------------
2017-03-06
I fixed this problem by adding fonts to Xcode project.
fonts are in Info.plist:
<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>Zocial.ttf</string>

You can get these font files from native-base library.

**Comment by lgwen425** [comment]
me too

**Comment by anxsec** [comment]
same problem

**Comment by zj-insist** [comment]
First ,you need to make sure `react-native-vector-icons` is linked，if not ,run `react-native link react-native-vector-icons`.Then checkout  `libRNVectorIcons.a` is exited.
If you recompile `libRNVectorIcons.a` ,there will be some problems ,you can solve it in
https://github.com/oblador/react-native-vector-icons/issues/375

**Comment by xiJieGuYuan** [comment]
same problem

**Comment by lgwen425** [comment]
first，run brew doctor ， checkout xcode tools is installed.
then，run react-native link react-native-vector-icons

**Comment by theho** [comment]
I am having the same problem...tried the above and didn't work.
Any other recommendation ?

**Comment by moxiaobei2** [comment]
same problem.

**Comment by rzrobert** [comment]
me too

**Comment by RookiePyl** [comment]
@zj-insist  comment can solve the problem。

**Comment by rob5408** [comment]
I had to reread the instructions, I had missed the Copy Bundle Resources step on iOS
