### ISSUE TITLE
win10， run-android 报错 ':app:processDebugResources'.

### ISSUE THREAD

**Issue by wcldyx** [fangwei716/ThirtyDaysOfReactNative#59]
react-native run android 报错，大神能帮忙看下这是什么问题
![image](https://user-images.githubusercontent.com/26700595/32847632-83c7f488-ca65-11e7-9571-bc42526ef3a7.png)

**Comment by afresh** [comment]
Execution failed for task ':app:prepareSrolkReactNativeFilePickerUnspecifiedLibrary'.

Could not expand ZIP .....node_modules\react-native-file-picker\android\build\outputs\aar\react-native-file-picker-release.aar
(on windows):
 
cd android 
gradlew clean 
cd ..
react-native run-android
or
 
cd android && gradlew clean && cd .. && react-native run-android

**Comment by Hideer** [comment]
楼上的 并 没有效果额；
Execution failed for task ':app:processDebugResources'

**Comment by Hideer** [comment]
@wcldyx  
My error message is the same as yours.

Can you give me some help?

**Comment by shougua** [comment]
> react-native run android 报错，大神能帮忙看下这是什么问题
> ![image](https://user-images.githubusercontent.com/26700595/32847632-83c7f488-ca65-11e7-9571-bc42526ef3a7.png)
请问是怎么解决的呀
